const {
  REACT_APP_WAVES_NODE_URL,
  REACT_APP_WAVES_PROVIDER_URL,
  REACT_APP_WAVES_EXPLORER_URL,
  REACT_APP_TOKEN_ASSET_ID,
  REACT_APP_TOKEN_ASSET_DECIMALS,
  REACT_APP_TOKEN_POOL
} = process.env

const WAVES_ASSET_ID = "WAVES"
const WAVES_DECIMALS = 8

export default {
  NODE_URL: REACT_APP_WAVES_NODE_URL,
  PROVIDER_URL: REACT_APP_WAVES_PROVIDER_URL,
  EXPLORER_URL: REACT_APP_WAVES_EXPLORER_URL,
  TOKEN_ID: REACT_APP_TOKEN_ASSET_ID,
  TOKEN_DECIMALS: parseInt(REACT_APP_TOKEN_ASSET_DECIMALS),
  WAVES_ID: WAVES_ASSET_ID,
  WAVES_DECIMALS: WAVES_DECIMALS,
  POOL_ADDRESS: REACT_APP_TOKEN_POOL
}