const { REACT_APP_WAVES_NODE_URL, REACT_APP_WAVES_PROVIDER_URL, REACT_APP_WAVES_EXPLORER_URL } = process.env
export default {
  NODE_URL: REACT_APP_WAVES_NODE_URL,
  PROVIDER_URL: REACT_APP_WAVES_PROVIDER_URL,
  EXPLORER_URL: REACT_APP_WAVES_EXPLORER_URL,
}