const { REACT_APP_WAVES_NODE_URL, REACT_APP_WAVES_PROVIDER_URL, REACT_APP_WAVES_EXPLORER_URL } = process.env
const BTFC_ASSET_ID = "AKemFVxKesFJeecAGqy1ujUK8YFa2hqewtucxAit7Z8c"
const BTFC_DECIMALS = 8
const WAVES_ASSET_ID = "WAVES"
const WAVES_DECIMALS = 8
export default {
  NODE_URL: REACT_APP_WAVES_NODE_URL,
  PROVIDER_URL: REACT_APP_WAVES_PROVIDER_URL,
  EXPLORER_URL: REACT_APP_WAVES_EXPLORER_URL,
  TOKEN_ID: BTFC_ASSET_ID,
  TOKEN_DECIMALS: BTFC_DECIMALS,
  WAVES_ID: WAVES_ASSET_ID,
  WAVES_DECIMALS: WAVES_DECIMALS,
}